### ISSUE TITLE
Clear Command Suggestion: remove /contact and /email as a tag

### ISSUE THREAD

**Issue by amoschee** [AY2425S1-CS2103T-F12-2/tp#148]
Since we are now considering duplicate person as people with same email or contact as mentioned in #133 clear /contact and /email would always delete 1 entry can be seen as an overlap with delete index command

**Comment by AgentHagu** [comment]
I think this might be confusing for users if the functionality is removed. The feature can be somewhat differentiated from delete since instead of doing `find` and then `delete`, they can do `clear` with the tags they used `find` with to delete those entries in 1 command.

Let me know what you think!
